name: Python Tests

on:
  push:
      branches: ["main"]
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

env:
  MIN_PYTHON: "3.10"

jobs:
  static:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
    - run: just install
    - run: just lint
    - run: just docs
    - run: just doctest
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    name: CPython ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
      - uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          local-atlas: '1'
      - run: just install
      - run: just test

  build-min:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v5
      with:
        enable-cache: true
        python-version: ${{ env.MIN_PYTHON }}
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
    - name: Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v5
      with:
        enable-cache: true
        python-version: ${{ env.MIN_PYTHON }}
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
    - uses: mongodb-labs/drivers-evergreen-tools@master
      with:
        local-atlas: '1'
    - name: Run unit tests with minimum dependency versions
      run: |
        uv sync --python=${MIN_PYTHON} --resolution=lowest-direct
        just test
